drop table if exists ccd_frl cascade;

CREATE TABLE ccd_frl (
	SCHOOL_YEAR TEXT, 
	FIPST TEXT, 
	STATENAME TEXT, 
	ST TEXT, 
	SCH_NAME TEXT, 
	STATE_AGENCY_NO TEXT, 
	UNION_TXT TEXT, 
	ST_LEAID TEXT, 
	LEAID TEXT, 
	ST_SCHID TEXT, 
	NCESSCH TEXT, 
	SCHID TEXT, 
	DATA_GROUP TEXT, 
	LUNCH_PROGRAM TEXT, 
	STUDENT_COUNT NUMERIC, 
	TOTAL_INDICATOR TEXT, 
	DMS_FLAG TEXT
);

\copy ccd_frl from 'data/frl.csv' csv header;
